default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: witty_cart_development
  username: postgres
  host: localhost
  template: template0

test:
  <<: *default
  database: witty_cart_test
  username: postgres
  min_messages: WARNING
  host: localhost
  template: template0
